// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: pack.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackHashData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionHashes [][]byte `protobuf:"bytes,1,rep,name=TransactionHashes,proto3" json:"TransactionHashes,omitempty"`
}

func (x *PackHashData) Reset() {
	*x = PackHashData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pack_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackHashData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackHashData) ProtoMessage() {}

func (x *PackHashData) ProtoReflect() protoreflect.Message {
	mi := &file_pack_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackHashData.ProtoReflect.Descriptor instead.
func (*PackHashData) Descriptor() ([]byte, []int) {
	return file_pack_proto_rawDescGZIP(), []int{0}
}

func (x *PackHashData) GetTransactionHashes() [][]byte {
	if x != nil {
		return x.TransactionHashes
	}
	return nil
}

type Pack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transactions  []*Transaction `protobuf:"bytes,1,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	AggregateSign []byte         `protobuf:"bytes,2,opt,name=AggregateSign,proto3" json:"AggregateSign,omitempty"`
	Hash          []byte         `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
	TimeStamp     int64          `protobuf:"varint,4,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
}

func (x *Pack) Reset() {
	*x = Pack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pack_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pack) ProtoMessage() {}

func (x *Pack) ProtoReflect() protoreflect.Message {
	mi := &file_pack_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pack.ProtoReflect.Descriptor instead.
func (*Pack) Descriptor() ([]byte, []int) {
	return file_pack_proto_rawDescGZIP(), []int{1}
}

func (x *Pack) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Pack) GetAggregateSign() []byte {
	if x != nil {
		return x.AggregateSign
	}
	return nil
}

func (x *Pack) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Pack) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type Packs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packs []*Pack `protobuf:"bytes,1,rep,name=Packs,proto3" json:"Packs,omitempty"`
}

func (x *Packs) Reset() {
	*x = Packs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pack_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packs) ProtoMessage() {}

func (x *Packs) ProtoReflect() protoreflect.Message {
	mi := &file_pack_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packs.ProtoReflect.Descriptor instead.
func (*Packs) Descriptor() ([]byte, []int) {
	return file_pack_proto_rawDescGZIP(), []int{2}
}

func (x *Packs) GetPacks() []*Pack {
	if x != nil {
		return x.Packs
	}
	return nil
}

type PackAggregateSignData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackHash   []byte   `protobuf:"bytes,1,opt,name=PackHash,proto3" json:"PackHash,omitempty"`
	PublicKeys [][]byte `protobuf:"bytes,2,rep,name=PublicKeys,proto3" json:"PublicKeys,omitempty"`
	Hashes     [][]byte `protobuf:"bytes,3,rep,name=Hashes,proto3" json:"Hashes,omitempty"`
	Sign       []byte   `protobuf:"bytes,4,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *PackAggregateSignData) Reset() {
	*x = PackAggregateSignData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pack_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackAggregateSignData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackAggregateSignData) ProtoMessage() {}

func (x *PackAggregateSignData) ProtoReflect() protoreflect.Message {
	mi := &file_pack_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackAggregateSignData.ProtoReflect.Descriptor instead.
func (*PackAggregateSignData) Descriptor() ([]byte, []int) {
	return file_pack_proto_rawDescGZIP(), []int{3}
}

func (x *PackAggregateSignData) GetPackHash() []byte {
	if x != nil {
		return x.PackHash
	}
	return nil
}

func (x *PackAggregateSignData) GetPublicKeys() [][]byte {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

func (x *PackAggregateSignData) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

func (x *PackAggregateSignData) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type VerifyPacksSignRequestHashData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackHashes [][]byte `protobuf:"bytes,1,rep,name=PackHashes,proto3" json:"PackHashes,omitempty"`
}

func (x *VerifyPacksSignRequestHashData) Reset() {
	*x = VerifyPacksSignRequestHashData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pack_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyPacksSignRequestHashData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPacksSignRequestHashData) ProtoMessage() {}

func (x *VerifyPacksSignRequestHashData) ProtoReflect() protoreflect.Message {
	mi := &file_pack_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPacksSignRequestHashData.ProtoReflect.Descriptor instead.
func (*VerifyPacksSignRequestHashData) Descriptor() ([]byte, []int) {
	return file_pack_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyPacksSignRequestHashData) GetPackHashes() [][]byte {
	if x != nil {
		return x.PackHashes
	}
	return nil
}

type VerifyPacksSignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash      []byte                   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	PacksData []*PackAggregateSignData `protobuf:"bytes,2,rep,name=PacksData,proto3" json:"PacksData,omitempty"`
}

func (x *VerifyPacksSignRequest) Reset() {
	*x = VerifyPacksSignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pack_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyPacksSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPacksSignRequest) ProtoMessage() {}

func (x *VerifyPacksSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pack_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPacksSignRequest.ProtoReflect.Descriptor instead.
func (*VerifyPacksSignRequest) Descriptor() ([]byte, []int) {
	return file_pack_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyPacksSignRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *VerifyPacksSignRequest) GetPacksData() []*PackAggregateSignData {
	if x != nil {
		return x.PacksData
	}
	return nil
}

type VerifyPackSignResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackHash []byte `protobuf:"bytes,1,opt,name=PackHash,proto3" json:"PackHash,omitempty"`
	Valid    bool   `protobuf:"varint,2,opt,name=Valid,proto3" json:"Valid,omitempty"`
}

func (x *VerifyPackSignResult) Reset() {
	*x = VerifyPackSignResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pack_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyPackSignResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPackSignResult) ProtoMessage() {}

func (x *VerifyPackSignResult) ProtoReflect() protoreflect.Message {
	mi := &file_pack_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPackSignResult.ProtoReflect.Descriptor instead.
func (*VerifyPackSignResult) Descriptor() ([]byte, []int) {
	return file_pack_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyPackSignResult) GetPackHash() []byte {
	if x != nil {
		return x.PackHash
	}
	return nil
}

func (x *VerifyPackSignResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type VerifyPacksSignResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestHash []byte                  `protobuf:"bytes,1,opt,name=RequestHash,proto3" json:"RequestHash,omitempty"`
	Results     []*VerifyPackSignResult `protobuf:"bytes,2,rep,name=Results,proto3" json:"Results,omitempty"`
}

func (x *VerifyPacksSignResult) Reset() {
	*x = VerifyPacksSignResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pack_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyPacksSignResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPacksSignResult) ProtoMessage() {}

func (x *VerifyPacksSignResult) ProtoReflect() protoreflect.Message {
	mi := &file_pack_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPacksSignResult.ProtoReflect.Descriptor instead.
func (*VerifyPacksSignResult) Descriptor() ([]byte, []int) {
	return file_pack_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyPacksSignResult) GetRequestHash() []byte {
	if x != nil {
		return x.RequestHash
	}
	return nil
}

func (x *VerifyPacksSignResult) GetResults() []*VerifyPackSignResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_pack_proto protoreflect.FileDescriptor

var file_pack_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x61,
	0x63, 0x6b, 0x1a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x0c, 0x50, 0x61, 0x63, 0x6b, 0x48, 0x61, 0x73,
	0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73,
	0x68, 0x65, 0x73, 0x22, 0x9c, 0x01, 0x0a, 0x04, 0x50, 0x61, 0x63, 0x6b, 0x12, 0x3c, 0x0a, 0x0c,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x41, 0x67,
	0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0d, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x29, 0x0a, 0x05, 0x50, 0x61, 0x63, 0x6b, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x50,
	0x61, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x61, 0x63,
	0x6b, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x52, 0x05, 0x50, 0x61, 0x63, 0x6b, 0x73, 0x22, 0x7f, 0x0a,
	0x15, 0x50, 0x61, 0x63, 0x6b, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x53, 0x69,
	0x67, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x63, 0x6b, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x50, 0x61, 0x63, 0x6b, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x06, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69,
	0x67, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x22, 0x40,
	0x0a, 0x1e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x50, 0x61, 0x63, 0x6b, 0x73, 0x53, 0x69, 0x67,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73,
	0x22, 0x67, 0x0a, 0x16, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x50, 0x61, 0x63, 0x6b, 0x73, 0x53,
	0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x39,
	0x0a, 0x09, 0x50, 0x61, 0x63, 0x6b, 0x73, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x41, 0x67, 0x67,
	0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09,
	0x50, 0x61, 0x63, 0x6b, 0x73, 0x44, 0x61, 0x74, 0x61, 0x22, 0x48, 0x0a, 0x14, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x50, 0x61, 0x63, 0x6b, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x50, 0x61, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x22, 0x6f, 0x0a, 0x15, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x50, 0x61, 0x63,
	0x6b, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x34,
	0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x50, 0x61, 0x63,
	0x6b, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x42, 0x26, 0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x69, 0x61, 0x69,
	0x76, 0x6e, 0x2e, 0x66, 0x69, 0x6e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x70, 0x61, 0x63, 0x6b, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pack_proto_rawDescOnce sync.Once
	file_pack_proto_rawDescData = file_pack_proto_rawDesc
)

func file_pack_proto_rawDescGZIP() []byte {
	file_pack_proto_rawDescOnce.Do(func() {
		file_pack_proto_rawDescData = protoimpl.X.CompressGZIP(file_pack_proto_rawDescData)
	})
	return file_pack_proto_rawDescData
}

var file_pack_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pack_proto_goTypes = []interface{}{
	(*PackHashData)(nil),                   // 0: pack.PackHashData
	(*Pack)(nil),                           // 1: pack.Pack
	(*Packs)(nil),                          // 2: pack.Packs
	(*PackAggregateSignData)(nil),          // 3: pack.PackAggregateSignData
	(*VerifyPacksSignRequestHashData)(nil), // 4: pack.VerifyPacksSignRequestHashData
	(*VerifyPacksSignRequest)(nil),         // 5: pack.VerifyPacksSignRequest
	(*VerifyPackSignResult)(nil),           // 6: pack.VerifyPackSignResult
	(*VerifyPacksSignResult)(nil),          // 7: pack.VerifyPacksSignResult
	(*Transaction)(nil),                    // 8: transaction.Transaction
}
var file_pack_proto_depIdxs = []int32{
	8, // 0: pack.Pack.Transactions:type_name -> transaction.Transaction
	1, // 1: pack.Packs.Packs:type_name -> pack.Pack
	3, // 2: pack.VerifyPacksSignRequest.PacksData:type_name -> pack.PackAggregateSignData
	6, // 3: pack.VerifyPacksSignResult.Results:type_name -> pack.VerifyPackSignResult
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pack_proto_init() }
func file_pack_proto_init() {
	if File_pack_proto != nil {
		return
	}
	file_transaction_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pack_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackHashData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pack_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pack_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pack_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackAggregateSignData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pack_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyPacksSignRequestHashData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pack_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyPacksSignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pack_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyPackSignResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pack_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyPacksSignResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pack_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pack_proto_goTypes,
		DependencyIndexes: file_pack_proto_depIdxs,
		MessageInfos:      file_pack_proto_msgTypes,
	}.Build()
	File_pack_proto = out.File
	file_pack_proto_rawDesc = nil
	file_pack_proto_goTypes = nil
	file_pack_proto_depIdxs = nil
}
